
default:
  model_class: 'sVAR'
  tau: 1.0e-6
  rho: 1
  max_admm_iter: 2000
  admm_tol: 0.01
  tol: 0.02
  max_epoch: 20
  threshold_A: 0.005
  threshold_B: 0.05

## setting: Gaussian, 10%
ds2-50:
  admm_tol: 0.0001
  nlags: 2
  mu_A: 0.02
  mu_B: 0.2
  mu_B_refit: 0.01

ds2-100:
  admm_tol: 0.0001
  nlags: 2
  mu_A: 0.035
  mu_B: 0.2
  mu_B_refit: 0.05

ds2-200:
  admm_tol: 0.0001
  nlags: 2
  mu_A: 0.07
  mu_B: 0.2
  mu_B_refit: 1.2

ds2-200-standardize:
  admm_tol: 0.001
  nlags: 2
  mu_A: 0.008
  mu_B: 0.1
  mu_B_refit: 0.02
