
default:
  model_class: 'sVAR'
  tau: 1.0e-6
  rho: 1
  max_admm_iter: 2000
  admm_tol: 0.01
  tol: 0.02
  max_epoch: 20
  threshold_A: 0.005
  threshold_B: 0.05

## setting: Laplace 5%
ds3-50:
  admm_tol: 0.0001
  nlags: 2
  mu_A: 0.05
  mu_B: 0.2
  mu_B_refit: 0.005

ds3-100:
  admm_tol: 0.0001
  nlags: 2
  mu_A: 0.04
  mu_B: 0.11
  mu_B_refit: 0.1

ds3-200:
  nlags: 2
  mu_A: 0.10
  mu_B: 0.2
  mu_B_refit: 0.8

ds3-200-standardize:
  nlags: 2
  mu_A: 0.03
  mu_B: 0.1
  mu_B_refit: 0.15
